Badges/Controllers/BadgeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Badges.Helpers;
using Badges.Models;
using Badges.Models.PostModels.Account;
using Badges.Models.PostModels.Badges;

namespace Badges.Controllers
{
    public class BadgeController : Controller
    {
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Update(string userId)
        {
            var reqHelper = new RequirementsHelper();
            await reqHelper.UpdateRequirements(userId);

            return RedirectToAction("Index");
        } 

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            using (var db = DbHelper.GetDb())
            {
                var badges = await db.Badges.ToListAsync();
                return View(badges);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            using (var db = DbHelper.GetDb())
            {
                var badge = await db.Badges.FirstOrDefaultAsync(b => b.Id == id);
                if (badge != null)
                {
                    db.Badges.Remove(badge);
                }

                await db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            using (var db = DbHelper.GetDb())
            {
                var badge = await db.Badges.Include(b => b.Requirements.Select(r => r.Parameters)).Include(b => b.Image).FirstOrDefaultAsync(b => b.Id == id);
                if (badge != null)
                {
                    return View(badge);
                }
                return Redirect("Error");
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create()
        {
            return View(new EditBadge());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EditBadge model)
        {
            if (ModelState.IsValid)
            {
                using (var db = DbHelper.GetDb())
                {
                    var badge = new Badge()
                    {
                        Description = model.Description,
                        Name = model.Name,
                        EstimatedHours = model.EstimatedHours
                    };

                    db.Badges.Add(badge);

                    await db.SaveChangesAsync();

                    return RedirectToAction("Edit", new {id = badge.Id});
                }
            }

            return Redirect("Error");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int id)
        {
            using (var db = DbHelper.GetDb())
            {
                var badge = await db.Badges.Include(b => b.Requirements.Select(r => r.Parameters))
                    .FirstOrDefaultAsync(b => b.Id == id);
                if (badge != null)
                {
                    var model = new EditBadge()
                    {
                        Description = badge.Description,
                        Name = badge.Name,
                        Id = badge.Id,
                        EstimatedHours = badge.EstimatedHours ?? 0,
                        ImageSource = badge.Image?.ImageString,
                        Requirements = badge.Requirements.Select(r => new EditRequirement()
                        {
                            Id = r.Id,
                            Text = r.Text,
                            Url = r.UrlForStatus,
                            Params = r.Parameters.Select(p => new EditParam()
                            {
                                Name = p.Name,
                                Value = p.Value
                            }).ToList()

                        }).ToList()
                    };

                    return View(model);
                }
            }

            return Redirect("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditBadge model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id.HasValue)
                {
                    using (var db = DbHelper.GetDb())
                    {
                        var badge = await db.Badges.Include(b => b.Requirements.Select(r => r.Parameters)).FirstOrDefaultAsync(b => b.Id == model.Id);

                        if (badge == null)
                        {
                            return RedirectToAction("Index");
                        }

                        badge.EstimatedHours = model.EstimatedHours;
                        badge.Description = model.Description;
                        badge.Name = model.Name;

                        if (badge.ImageId == null)
                        {
                            badge.Image = new Image();
                        }

                        var matches = Regex.Match(model.ImageSource ?? "", @"data:image/(?<type>.+?),(?<data>.+)");
                        var type = matches.Groups["type"]?.Value ?? "";
                        var data = matches.Groups["data"]?.Value ?? "";
                        
                        badge.Image.ImageData = Convert.FromBase64String(data);
                        badge.Image.Type = type;

                        //Clear deleted requirements
                        foreach (var requirement in badge.Requirements.ToList())
                        {
                            if (!model.Requirements.Any(r => r.Id == requirement.Id))
                            {
                                badge.Requirements.Remove(requirement);
                                foreach (var param in requirement.Parameters.ToList())
                                {
                                    db.Entry(param).State = EntityState.Deleted;
                                }
                                db.Entry(requirement).State = EntityState.Deleted;
                            }
                        }
                        //Add or modify new ones
                        foreach (var requirement in model.Requirements)
                        {
                            var dbReq = badge.Requirements.FirstOrDefault(r => r.Id == requirement.Id) ?? new Requirement();
                            dbReq.Text = requirement.Text;
                            dbReq.UrlForStatus = requirement.Url;
                            //Clear params
                            foreach (var param in dbReq.Parameters.ToList())
                            {
                                dbReq.Parameters.Remove(param);
                                db.Entry(param).State = EntityState.Deleted;;
                            }
                            //Add new ones
                            dbReq.Parameters = requirement.Params.Select(p => new Parameter()
                            {
                                Name = p.Name,
                                Value = p.Value
                            }).ToList();

                            badge.Requirements.Add(dbReq);
                        }

                        await db.SaveChangesAsync();

                        return RedirectToAction("Index");
                    }
                }
            }

            return View(model);
        }
    }
}

Badges/Views/Shared/_Layout.cshtml
@using Badges.Models.Auth
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OU Badges</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("styles", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Dashboard", "Home")" class="navbar-brand"><span class="glyphicon-asterisk"></span>Badges</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Dashboard", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown dropdown-hover">
                            <a href="#">Admin<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                                <li>@Html.ActionLink("Roles", "Roles", "Admin")</li>
                                <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                                <li>@Html.ActionLink("Badges", "Index", "Badge")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>
    
<footer>
    <p>Badges Demo <a href="mailto:admin@ouprojects.com">Contact</a></p>
</footer>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>